name: Publish release
on:
  push:
    branches:
      - master

jobs:
  run:
    runs-on: macos-latest

  steps:
  - uses: actions/checkout@v4
  - run: pip install -r requests
  - run: python -u make_release.py
    timeout-minutes: 10
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

